# Generated by Django 5.1 on 2025-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationinfo',
            name='additional_information',
        ),
    ]
