# Generated by Django 5.1 on 2025-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_configurationinfo_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationinfo',
            name='lo_ref_signal_freq_mhz',
            field=models.CharField(help_text='LO ref signal frequency in MHz.', max_length=150),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='s_band_freq_bandpass_mhz',
            field=models.CharField(help_text='S band frequency bandpass in MHz.', max_length=150),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='x_band_freq_bandpass_mhz',
            field=models.CharField(help_text='X band frequency bandpass in MHz.', max_length=150),
        ),
    ]
