# Generated by Django 5.1 on 2025-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_configurationinfo_lo_ref_signal_freq_mhz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationinfo',
            old_name='primary_administrative_agency_contact',
            new_name='primary_administrative_agency_contact_person',
        ),
        migrations.RemoveField(
            model_name='configurationinfo',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='configurationinfo',
            name='alternative_agency_URL_of_agency_web_page',
            field=models.URLField(blank=True, help_text='Mention the URL of the alternative agency web page.', null=True),
        ),
        migrations.AddField(
            model_name='configurationinfo',
            name='alternative_agency_postal_address',
            field=models.CharField(default='80333 Munich', help_text='Mention the alternative agency postal address.', max_length=250),
        ),
        migrations.AddField(
            model_name='configurationinfo',
            name='alternative_agency_shipping_address',
            field=models.CharField(default='Arcisstr. 21', help_text='Mention the alternative agency shipping address.', max_length=250),
        ),
    ]
