# Generated by Django 5.1 on 2025-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_rename_primary_administrative_agency_contact_configurationinfo_primary_administrative_agency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationinfo',
            name='alternative_agency_postal_address',
            field=models.CharField(default='Arcisstr. 21, 80290 Munich', help_text='Mention the alternative agency postal address.', max_length=250),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='alternative_agency_shipping_address',
            field=models.CharField(default='Arcisstr. 21, 80333 Munich', help_text='Mention the alternative agency shipping address.', max_length=250),
        ),
    ]
