# Generated by Django 4.2.20 on 2025-07-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0005_alter_configurationinfo_alternative_agency_postal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationinfo',
            name='update_date',
            field=models.DateField(blank=True, help_text='The updated Date.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='user',
            field=models.OneToOneField(help_text='The user who created this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to=settings.AUTH_USER_MODEL),
        ),
    ]
