# Generated by Django 4.2.20 on 2025-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_configurationinfo_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationinfo',
            name='CDP_monument_number',
            field=models.IntegerField(blank=True, default=0, help_text='CDP monument number.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='CDP_occupation_code',
            field=models.IntegerField(blank=True, default=0, help_text='CDP occupation code.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='X_down_converter_freq',
            field=models.FloatField(blank=True, default=0.0, help_text='X down converter frequency in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='computer_CPU_speed_in_MHz',
            field=models.FloatField(blank=True, default=0.0, help_text="Mention the computer's CPU speed in MHz.", null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='computer_disk_in_Gbytes',
            field=models.FloatField(blank=True, default=0.0, help_text="Mention the computer's disk in Gbytes.", null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='computer_memory_in_Mbytes',
            field=models.FloatField(blank=True, default=0.0, help_text="Mention the computer's memory in Mbytes.", null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='diameter_m',
            field=models.FloatField(blank=True, default=0.0, help_text='Diameter of the antenna in meters.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='end_date_of_occupation',
            field=models.DateField(blank=True, default=None, help_text='The end date of occupation.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='length_of_cable_run_m',
            field=models.FloatField(blank=True, default=0.0, help_text='Length of cable run in meters.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='most_recent_survey_date',
            field=models.DateField(blank=True, default=None, help_text='The most recent survey date.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers in video converter set.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers_with_16mhz_filter',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers with 16 MHz filter in all sideband outputs.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers_with_2mhz_filter',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers with 2 MHz filter in all sideband outputs.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers_with_32mhz_filter',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers with 32 MHz filter in all sideband outputs.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers_with_4mhz_filter',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers with 4 MHz filter in all sideband outputs.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_mixers_with_8mhz_filter',
            field=models.IntegerField(blank=True, default=0, help_text='Number of mixers with 8 MHz filter in all sideband outputs.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='number_of_recorders',
            field=models.IntegerField(blank=True, default=0, help_text='Number of recorders.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='phase_cal_ref_signal_freq_mhz',
            field=models.FloatField(blank=True, default=0.0, help_text='Phase cal ref signal frequency in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='pressure_sensor_height_relative_to_VLBI_in_meters',
            field=models.FloatField(blank=True, default=0.0, help_text='Mention the height relative to VLBI in meters.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='s_bandwidth_mhz',
            field=models.FloatField(blank=True, default=0.0, help_text='S bandwidth in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='s_lo_frequencies_mhz',
            field=models.FloatField(blank=True, default=0.0, help_text='S LO frequencies in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='s_sefd_jy',
            field=models.FloatField(blank=True, default=0.0, help_text='S SEFD in Jy.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='s_tsys_at_zenith_k',
            field=models.FloatField(blank=True, default=0.0, help_text='S Tsys at zenith in K.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='start_date_of_occupation',
            field=models.DateField(blank=True, default=None, help_text='The start date of occupation.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='start_date_of_operation',
            field=models.DateField(blank=True, default=None, help_text='The start date of configuration operation.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='update_date',
            field=models.DateField(blank=True, default=None, help_text='The updated Date.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='x_bandwidth_mhz',
            field=models.FloatField(blank=True, default=0.0, help_text='X bandwidth in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='x_lo_frequencies_mhz',
            field=models.FloatField(blank=True, default=0.0, help_text='X LO frequencies in MHz.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='x_sefd_jy',
            field=models.FloatField(blank=True, default=0.0, help_text='X SEFD in Jy.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationinfo',
            name='x_tsys_at_zenith_k',
            field=models.FloatField(blank=True, default=0.0, help_text='X Tsys at zenith in K.', null=True),
        ),
    ]
