# Generated by Django 4.2.20 on 2025-09-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_configurationinfo_cdp_monument_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationinfo',
            name='responsible_agency_postal_address',
            field=models.CharField(blank=True, default='', help_text='Mention the postal address.', max_length=250),
        ),
        migrations.AddField(
            model_name='configurationinfo',
            name='responsible_agency_shipping_address',
            field=models.CharField(blank=True, default='', help_text='Mention the shipping address.', max_length=250),
        ),
    ]
