# Generated by Django 5.1 on 2025-02-14 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the person making the request.', max_length=100)),
                ('agency', models.CharField(help_text='Agency name of the requester.', max_length=150)),
                ('email', models.EmailField(help_text='Email address of the requester.', max_length=254)),
                ('date', models.DateField(help_text='Date of the request.')),
                ('site_name', models.CharField(help_text='Name of the site.', max_length=100)),
                ('country', models.CharField(help_text='Country where the site is located.', max_length=50)),
                ('point_description', models.CharField(help_text='Description of the point.', max_length=500)),
                ('support_description', models.CharField(blank=True, help_text='Description of the support (optional).', max_length=500, null=True)),
                ('picture', models.ImageField(blank=True, help_text='Upload an optional image (optional).', null=True, upload_to='images/')),
                ('domes_number', models.DecimalField(decimal_places=9, help_text='Domes identification number.', max_digits=20)),
                ('local_number', models.CharField(help_text='Local identification number.', max_length=50)),
                ('four_char_code', models.CharField(help_text='4-character site code.', max_length=10)),
                ('latitude_deg_min', models.CharField(help_text='Latitude in degrees and minutes.', max_length=50)),
                ('longitude_deg_min', models.CharField(help_text='Longitude in degrees and minutes.', max_length=50)),
                ('elevation_m', models.FloatField(help_text='Elevation in meters.')),
                ('tectonic_plate', models.CharField(blank=True, help_text='Name of the tectonic plate (optional).', max_length=100, null=True)),
                ('instrument', models.CharField(help_text='Name of the installed instrument.', max_length=200)),
                ('date_of_installation', models.DateField(help_text='Date of the instrument installation.')),
                ('operation_contact_name', models.CharField(help_text='Full name of the operation contact.', max_length=100)),
                ('operation_agency', models.CharField(help_text='Agency name of the operation contact.', max_length=250)),
                ('operation_email', models.EmailField(help_text='Email of the operation contact.', max_length=254)),
                ('site_contact_name', models.CharField(help_text='Full name of the site contact.', max_length=100)),
                ('site_agency', models.CharField(help_text='Agency name of the site contact.', max_length=250)),
                ('site_email', models.EmailField(help_text='Email of the site contact.', max_length=254)),
                ('additional_info', models.TextField(blank=True, help_text='Additional information or comments (optional).', null=True)),
                ('user', models.ForeignKey(help_text='The user who created this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='antenna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
