# Generated by Django 5.1 on 2025-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennainfo',
            name='domes_number',
            field=models.CharField(help_text='Domes identification number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='antennainfo',
            name='four_char_code',
            field=models.CharField(help_text='4-character site code.', max_length=4),
        ),
    ]
