# Generated by Django 5.1 on 2025-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0002_alter_antennainfo_domes_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antennainfo',
            name='operation_email',
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='operation_email_one',
            field=models.EmailField(default='example@example.com', help_text='Email of the first operation contact.', max_length=254),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='operation_email_two',
            field=models.EmailField(blank=True, help_text='Email of the second operation contact (optional).', max_length=254, null=True),
        ),
    ]
