# Generated by Django 5.1 on 2025-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0003_remove_antennainfo_operation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennainfo',
            name='city_or_town',
            field=models.CharField(default='Munich', help_text='City or Town where the site is located.', max_length=50),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='source_of_position',
            field=models.CharField(blank=True, help_text="Name of the position's source (optional).", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='state_or_province',
            field=models.CharField(default='Bayern', help_text='State or Province where the site is located.', max_length=50),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='x_coordinate_m',
            field=models.FloatField(default='0', help_text='X coordinate in meters.'),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='y_coordinate_m',
            field=models.FloatField(default='0', help_text='Y coordinate in meters.'),
        ),
        migrations.AddField(
            model_name='antennainfo',
            name='z_coordinate_m',
            field=models.FloatField(default='0', help_text='Z coordinate in meters.'),
        ),
        migrations.AlterField(
            model_name='antennainfo',
            name='country',
            field=models.CharField(default='Germany', help_text='Country where the site is located.', max_length=50),
        ),
        migrations.AlterField(
            model_name='antennainfo',
            name='full_name',
            field=models.CharField(help_text='Full name of the person making the request.', max_length=150),
        ),
    ]
