# Generated by Django 5.1 on 2025-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0004_antennainfo_city_or_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennainfo',
            name='city_or_town',
            field=models.CharField(default='Koetzting', help_text='City or Town where the site is located.', max_length=50),
        ),
    ]
