# Generated by Django 4.2.20 on 2025-06-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antenna', '0005_alter_antennainfo_city_or_town'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennainfo',
            options={'verbose_name_plural': 'Antenna Information'},
        ),
        migrations.AlterField(
            model_name='antennainfo',
            name='user',
            field=models.OneToOneField(help_text='The user who created this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='antenna', to=settings.AUTH_USER_MODEL),
        ),
    ]
