# Generated by Django 5.1 on 2025-03-29 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The current entry date and time.')),
                ('event_time', models.DateTimeField(help_text='Please enter the event date and time.')),
                ('technician_editor', models.TextField(blank=True, help_text='Please enter the main Editor/User technician name.', null=True)),
                ('participants', models.TextField(blank=True, help_text='Please enter other possible participants name.', null=True)),
                ('telescope', models.CharField(help_text='Please enter the Telescope name.', max_length=100)),
                ('component', models.CharField(blank=True, choices=[('1.1', 'Radio telescope'), ('1.1.1', 'Servosystem / Drives / Power Electronics'), ('1.1.2', 'Antenna Control System'), ('1.1.3', 'Cabeling'), ('1.1.4', 'Mechanics'), ('1.1.5', 'Pointing'), ('1.2', 'Frontend'), ('1.2.1', 'RF Receiver'), ('1.2.2', 'Cryo system / Dewar'), ('1.2.3', 'Local oscillator'), ('1.2.4', 'IF converter / Down-Converter / Up-Down-Converter'), ('1.3', 'Backend'), ('1.3.1', 'IF distributor'), ('1.3.2', 'Baseband converter (DBBC/RDBE/FILA10G/etc.)'), ('1.3.3', 'Data transfer network'), ('1.3.4', 'Recorder (Mark6/Flexbuff/etc.)'), ('1.4', 'Calibration systems'), ('1.4.1', 'Cable calibration system'), ('1.4.2', 'Phasen calibration system'), ('1.4.3', 'Noise calibration system'), ('1.4.4', 'Other calibration systems'), ('1.5', 'Time and frequency'), ('1.5.1', 'Maser'), ('1.5.2', 'GNSS time receiver'), ('1.5.3', 'Time and frequency distribution system'), ('1.5.4', 'Counter / Dotmon (fmout-gps)'), ('1.6', 'Control and Monitoring System'), ('1.6.1', 'NASA Field System'), ('1.6.2', 'Station code'), ('1.6.3', 'Monitoring system'), ('1.7', 'IT infrastructure'), ('1.7.1', 'Network (LAN)'), ('1.7.2', 'Internet'), ('1.7.3', 'Transfer server hardware'), ('1.7.4', 'Local correlator'), ('1.7.5', 'Other hardware'), ('1.8', 'Sensors'), ('1.8.1', 'Meteorology (Pressure, Temperature, Humidity, Wind speed, Wind direction)'), ('1.8.2', 'Other (Radiometer, Tower temps.)'), ('1.9', 'Building infrastructure'), ('1.9.1', 'Air conditioning'), ('1.9.2', 'Power / UPS'), ('1.10', 'Buildings'), ('1.11', 'Known RFI'), ('1.11.1', 'Terrestrial RFI (e.g. 5G / Radar / in-house)'), ('1.11.2', 'Satellite signals (e.g. Starlink)'), ('1.11.3', 'Local sender (e.g. DORIS)')], help_text='Please select the component.', max_length=100, null=True)),
                ('new_component', models.CharField(blank=True, help_text='Add a new component if needed.', max_length=100, null=True)),
                ('detailed_info', models.CharField(blank=True, help_text='Please enter the detailed information about the log entry.', max_length=350, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Please upload any relevant helpful pdfs, files, or images like a diagram plot or a quality plot.', null=True, upload_to='attachments/')),
                ('user', models.ForeignKey(help_text='The user who created this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
